{ IF NOT DEF(__LIBRARYNAMESPACEANDVERSION__)}
    {DEFINE __LIBRARYNAMESPACEANDVERSION__}
    {DEFINE LibraryNamespaceAndVersion Libs.MPXone_Medium_Core_v1_8_6}
    {DEFINE LibraryName 'MPXone_Medium_Core'}
    {DEFINE LibraryVersion 'MPXone_Medium_Core_v1_8_6'}
    {DEFINE LibraryVersionMajor 1}
    {DEFINE LibraryVersionMinor 8}
    {DEFINE LibraryVersionBuild 6}
    {DEFINE LibraryVersionType ''}
{ENDIF}