(**
    Initial Creation:
    3/5/2020
    Joshua Meduoye
    Component Level A
    Dover Food and Retail Defrost System Management
        ******
        This component is focused on software development on system defrost Control
        There are 2 major parts
        
        1. Features 
            Features contain software focused on creating new functionality
            
        2. Diagnostics 
            Diagnostics are focused on failure detection and troubleshooting
               
        ******
**)

(**
    Dew Point Calculation
        Dew Point is the temperature at which we can cool the air in order for water to condense.
        Inputs: Relative Humidity 
                Temperature
                

**)

