(**
    Initial Creation:
    3/5/2020
    Joshua Meduoye
    Component Level A
    Dover Food and Retail Frost Control System
        ******
        This component is focused on software development focused on Product Frost Control
        There are 2 major parts
        
        1. Features 
            Features contain software focused on creating new functionality
            
        2. Diagnostics 
            Diagnostics are focused on failure detection and troubleshooting
               
        ******
**)