(**
    Initial Creation:
    3/5/2020
    Joshua Meduoye
    Component Level B
    Dover Food and Retail Door System Management
        ******
        This component is focused on software development on Door Systems
        There are 2 major parts
        
        1. Features 
            Features contain software focused on creating new functionality
            
        2. Diagnostics 
            Diagnostics are focused on failure detection and troubleshooting
               
        ******
**)



(**

    Features: Door Open Detection
    Features
    Features 
**)

(**
    Feature Name: Door Open Detection
    ***
    Door Open detection has 3 major Modes
    1. Door Open Detection with Door Switch
    2. Door Open Detection without Door Switch (Return Air)
    3. Door Open Detection without Door Switch (Supply Air)
    
    
    ***
**)

(**
**)


