(**
    Initial Creation:
    3/5/2020
    Joshua Meduoye
    Component Level B
    Dover Food and Retail Lights Management
        ******
        This component is focused on software development on Lights controls system
        There are 2 major parts
        
        1. Features 
            Features contain software focused on creating new functionality
            
        2. Diagnostics 
            Diagnostics are focused on failure detection and troubleshooting
               
        ******
**)