{ IF NOT DEF(__LIBRARYNAMESPACEANDVERSION__)}
    {DEFINE __LIBRARYNAMESPACEANDVERSION__}
    {DEFINE LibraryNamespaceAndVersion Libs.SignalGeneration_v0_2_0}
    {DEFINE LibraryName 'SignalGeneration'}
    {DEFINE LibraryVersion 'SignalGeneration_v0_2_0'}
    {DEFINE LibraryVersionMajor 0}
    {DEFINE LibraryVersionMinor 2}
    {DEFINE LibraryVersionBuild 0}
    {DEFINE LibraryVersionType ''}
{ENDIF}